### ISSUE TITLE
如何用AirGoo反代Facebook？

### ISSUE THREAD

**Issue by keen88** [spance/AirGoo#24]
RT,如何用AirGoo反代Facebook？
用了反代谷歌，效果果然不错，特别是无需二次跳转很牛逼^-^

**Comment by tvvocold** [comment]
lol,fb 就不要想了，太大

**Comment by spance** [comment]
fb整个站是一个很大的应用，分别要处理html/js/css/ajax/cookie等等这种资源上的绝对路径，而分析这些路径和写这些路径规则是一件工作量很大的事情，时间和精力都是问题，所以说目前很难实现吧。

**Comment by keen88** [comment]
了解，有谷歌用就满足了
