### ISSUE TITLE
centOS6.5下貌似反代失败

### ISSUE THREAD

**Issue by mountainguan** [spance/AirGoo#27]
在日本东京的VPS下已经安装好node.js，
iptables已经添加了“-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT”这句在“-A INPUT -j REJECT --reject-with icmp-host-prohibited”的前面，
也安装好了ngnix，但尚未启动和配置ngnix(据说个人使用的话不配置ngnix也能用)。
然后upstart不知道是不是就是添加/etc/init/AirGoo.conf这个文件(本人服务器小白)。下面的是返回的内容

node server.js -a 0.0.0.0 -p 8080
4 Mar 15:18:02 - * - AirGoo-Server v1.1.4 started on 4:0.0.0.0:8080
4 Mar 15:18:09 - 113.105.128.252 - WARN - Not found the `x-forwarded-host` header from request and config.
4 Mar 15:18:09 - 113.105.128.252 - WARN - Not found the `x-forwarded-proto` header from request and config.
4 Mar 15:18:09 - 113.105.128.252 - redirect to https from 157.7.52.137:8080/

**Comment by keen88** [comment]
额，nginx必须启动吧

**Comment by spance** [comment]
日志看到只是2个警告，本意上那2个变量的值从nginx调用时获取的。
当然不用nginx做前端也是可以的，那就是只用AirGoo的http服务，但是当你的搜索中存在关键字后，会被tcp reset，所以说推荐使用nginx做前端，并由nginx来提供https服务和其它的访问控制等等，还是有好处的。

**Comment by mountainguan** [comment]
问题是我跟你你的教程还是搭到一般就混乱了= =nginx没配置过，不会弄，不知道文件的文件，也不知道自己配置的东西有没有问题。

**Comment by mountainguan** [comment]
而且貌似自动打开的是https://157.7.52.137:8080/而不是http，我nginx启动失败了，所以就不启动了

**Comment by spance** [comment]
你的描述不太容易看懂。
如果你不想用nginx那么把config.json中的force_https改为false 如果你需要nginx配置方面的参考帮助请参看wiki的 https://github.com/spance/AirGoo/wiki/%E5%89%8D%E7%AB%AFNginx%E9%85%8D%E7%BD%AE%E7%A4%BA%E6%84%8F

**Comment by mountainguan** [comment]
TAT能不能出个一键安装的脚本

**Comment by spance** [comment]
安装只有2步，下载、运行。配置部分，是要根据环境自定的，“一键”实在没有这个必要，也无法实现配置。
凡是一键的东西不是缺这个就是少那个，凡是一键的东西少了操作但多了麻烦，2个凡是，对于大多数一键类的东西都是适用的。
