### ISSUE TITLE
非常犀利

### ISSUE THREAD

**Issue by lampchop** [spance/AirGoo#33]
测试成功，犀利。不过图片搜索目前前面几张正常，后面的图片就无限制重复前面的了，亲看看是不是有这个问题哈。

**Comment by liyangyijie** [comment]
nginx 配置中下面的值 按如下修改
proxy_cache_key         $host$uri$is_args$args;
然后清理一下缓存

**Comment by tvvocold** [comment]
@spance 
图片搜索确实有bug, 我这里是只显示前几张图片。

**Comment by spance** [comment]
我这看没问题。
用chrome按F12到network面板，然后搜，把截图发出来看看。

**Comment by lampchop** [comment]
@liyangyijie 正解，搞定

**Comment by spance** [comment]
@liyangyijie 没错，感谢指正。的确是wiki示意配置项中忽略了args造成cache被重复利用。

**Comment by lampchop** [comment]
@spance 能多给一些文档吗 关于自定义修改，比如修改图标，网站标题之类的 谷歌那么显眼的logo，感觉很危险

**Comment by tvvocold** [comment]
https://github.com/spance/AirGoo/issues/30

**Comment by lampchop** [comment]
@spance 另外ios手机端搜索图片不能加载很多 往下拉 到最后就会出现 纯的图片色块，而没有图片内容了，亲看看有没有这个问题啊

**Comment by spance** [comment]
试了下没发现问题，滑了很多页页都出来了。你看看是不是到你服务器的网络不够好。

**Comment by spance** [comment]
Logo标题之类刺眼只是个我们主管感受，只要不公开私用，不要招致人工介入还不会有问题。

**Comment by tvvocold** [comment]
@spance 
问题是因为做这种反代被 abuse 了很多账号了，包括 PaaS 和 域名 都被封禁了。

**Comment by spance** [comment]
@tvvocold 被谁认为abuse? google?  被封禁了是什么情况？是被谁封了？

**Comment by tvvocold** [comment]
域名商，paas都被封过

**Comment by spance** [comment]
从你的服务器发往Google的请求不是足够的多是难以构成abuse.
封不封的事，应该要考虑换一个TOS可接受的供应商，这与程序无关。

**Comment by tvvocold** [comment]
事实是，已构成 abuse 了，因此我被封了很多账户了。惨痛的教训。

**Comment by lampchop** [comment]
@tvvocold 看来亲玩的有点大。还是设置访问验证吧，不然估计得坑爹。这个东西是很好的，摸头

**Comment by spance** [comment]
程序的原意就是要原模原样的还原。
无论是被abuse还是被供应商踢，这都与程序本身无关。
咨询你的服务器提供商查询TOS可接受的范围，这不是程序可及的。
好比刀子的问题，在什么样的环境态势、以什么样的姿势、怎么样使用刀子，人是有主观思考和选择能力的，或者说这就是人的问题。

**Comment by lampchop** [comment]
@spance  电脑端没有这个问题的，手机端加载第二页图片会这样，亲看看哈
![qq 20150707132733](https://cloud.githubusercontent.com/assets/12220151/8539308/408a1cf2-24ac-11e5-83b7-315280b7d563.png)

**Comment by spance** [comment]
@lampchop 我试过了，iOS8 Safari翻了很多，没看到问题。
你可以把你的访问地址和搜索关键字发邮件给我。

**Comment by lampchop** [comment]
@spance 邮件已发

**Comment by spance** [comment]
382bf9f6cc96a44b968ee83031d6d5e9843de951 已更新，应该已经解决这个问题。

**Comment by lampchop** [comment]
@spance 完美！顺便手机单击图片无法查看是黑色的可以解决吗，前几张可以查看放大，后面就不行了
![111](https://cloud.githubusercontent.com/assets/12220151/8571163/95e7c274-25b7-11e5-803f-b1deb8b83607.png)

**Comment by spance** [comment]
@lampchop 缩略图来自google也就是反代，而大图预览时候是从源站加载的，如果源站是blocked目标，那么加载就会失败自然就黑了。

**Comment by lampchop** [comment]
@spance 但是电脑可以呀

**Comment by spance** [comment]
@lampchop 有个替换错误，刚已经修复了。取最新1.1.5分支

**Comment by lampchop** [comment]
@spance 一夜回到解放前，无法放大，还有色块啦^_^.我先用1.1.4吧
等有时间再来反馈，楼主的这个项目很犀利

**Comment by spance** [comment]
@lampchop 确定是最后1.1.5吗？还有缓存清理了吗？safari的缓存在设置里面清理。
